site_name: Numen-rpg wiki
repo_url: https://github.com/Vergenter/numen-rpg_wiki
theme:
  name: material
  language: en
  features:
    - navigation.sections
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.code.copy
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - footnotes
  - attr_list
  - def_list
  - pymdownx.superfences
plugins:
  - search:
      prebuild_index: true
      lang: ["en"]
  - tags:
      tags_file: tags.md
  - awesome-pages
  - glightbox
  - minify:
      minify_html: true
  - redirects
extra_css:
  - styles/extra.css
nav:
  - Home: index.md
  - Rules: rules/index.md
  - World: world/index.md
  - Creatures: creatures/index.md
